spring:
  datasource:
    url: jdbc:h2:mem:NOXX_SERVICE_DATABASE;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MODE=MYSQL
    driver-class-name: org.h2.Driver
    password:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
      path: /database
logging:
  level:
    com:
      nerosec:
        noxx: DEBUG